# Reference: http://www.appveyor.com/docs/appveyor-yml
# Notes:
#   - Indent each level of configuration with 2 spaces. Do not use tabs!

#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 1.0.0.{build}
image: Visual Studio 2017

#---------------------------------#
#    environment configuration    #
#---------------------------------#

environment:
  smallversion: 1.0.0
  NugetKey:
    secure: tYPzvkyTyLs55bvneeVzag8tp+r3qjFlRbLcllo4g/g96oMBBxhd+p3wzxZHUvgk
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-$(configuration)'

#---------------------------------#
#       build configuration       #
#---------------------------------#

configuration:
 - Debug
 - Release
platform: Any CPU
build:
  parallel: true
  verbosity: minimal
  publish_nuget: true
after_build:
#ClientUpdater post build commands
 - ps: mkdir "$env:appveyor_build_folder\FinalFiles\$env:configuration\LunaConfigNode"
 - ps: xcopy /s/y "$env:appveyor_build_folder\LunaConfigNode\bin\$env:configuration\*.*" "$env:appveyor_build_folder\FinalFiles\$env:configuration\LunaConfigNode"
 #7zip everything
 - ps: 7z a "$env:appveyor_build_folder\LunaConfigNode-$env:configuration.zip" "$env:appveyor_build_folder\FinalFiles\$env:configuration\LunaConfigNode"
#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
 - path: .\LunaConfigNode-$(configuration).zip
   name: LunaConfigNode-$(configuration).zip
#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:
 - provider: GitHub
   tag: $(smallversion)-Draft
   release: LunaConfigNode $(smallversion)-Draft
   description: 'Build $(appveyor_build_version)'
   artifact: LunaConfigNode-$(configuration).zip
   auth_token:
    secure: zWJqDvz3LjR2J358JIJKICwghW/DWRzs73KWb3KApTLOreA4c8DN1tos+O3qBMR7
   draft: true
   force_update: true
   on:
    branch: master

 - provider: NuGet
   server: #NuGet.org
   api_key:
    secure: tYPzvkyTyLs55bvneeVzag8tp+r3qjFlRbLcllo4g/g96oMBBxhd+p3wzxZHUvgk
   skip_symbols: false
   symbol_server: #SymbolSource.org
   artifact: /.*\.nupkg/